steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/djkeshawa/cc-crypto-exchange.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1-docker.pkg.dev/coastal-haven-337718/crypto-exchange:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/coastal-haven-337718/crypto-exchangelatest']