steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/djkeshawa/cc-crypto-exchange.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build','-t','us-central1-docker.pkg.dev/coastal-haven-337718/crypto-exchange/crypto:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push','us-central1-docker.pkg.dev/coastal-haven-337718/crypto-exchange/crypto:latest']

# This step deploys the new version of container image
# in the hcrypto-cluster Kubernetes Engine cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=crypto-cluster'

# This step is to deploy the service
- name: 'gcr.io/cloud-builders/kubectl'
  id: Service
  args:
  - 'apply'
  - '-f'
  - 'service.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=crypto-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Secrets
  args:
  - 'create'
  - 'secret'
  - 'generic'
  - 'mongoPassword'
  - '--from-literal=MONGO_PASSWORD=${_MONGO_PASSWORD}'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=crypto-cluster'
