apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange-01.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-exchange-v1.1.0
  template:
    metadata:
      labels:
        app: crypto-exchange-v1.1.0
    spec:
      containers:
      - name: crypto-exchange
        image: IMAGE_NAME
        livenessProbe:
             httpGet:
                path: /
                port: 8080
        readinessProbe:
             httpGet:
                path: /
                port: 8080
        lifecycle:
             preStop:
                exec:
                   command: ["/bin/bash", "-c", "sleep 5"]
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongopassword
                key: MONGO_PASSWORD